//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOTNET.LOGS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LogMain()
        {
            this.LogDetails = new HashSet<LogDetail>();
        }
    
        public int LogId { get; set; }
        public Nullable<System.DateTime> LogDateTime { get; set; }
        public string AspNetSessionID { get; set; }
        public string CustomerSessionID { get; set; }
        public string ClientAddress { get; set; }
        public string IsMobileDevice { get; set; }
        public string UserAgent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LogDetail> LogDetails { get; set; }
    }
}
