//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DOTNET.LOGS.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MIAdditionalItemLog
    {
        public int MIAdditionalItemsLogsId { get; set; }
        public int MILogsId { get; set; }
        public string AdditionalItemKey { get; set; }
        public string AdditionalItemValue { get; set; }
        public Nullable<System.DateTime> LogDateTime { get; set; }
    
        public virtual MILog MILog { get; set; }
    }
}
